import sys
sys.path.append('../colmap-manage/')
sys.path.append('../camera-manage/')

from colmap_manage.Module.colmap_manager import COLMAPManager
from colmap_manage.Module.dataset_manager import DatasetManager
from neural_angelo.Method.train import trainNA

data_folder_name = 'NeRF/3vjia_simple'
video_file_path = 'None'
down_sample_scale = 1
resolution = 8

scale = 1
show_image = False
print_progress = True
remove_old = False
remain_db = True
valid_percentage = 0.8
method_dict = {
    'scene_type': 'outdoor',
}

data_folder_path = '/home/chli/Dataset/' + data_folder_name + '/'
dataset_folder_path = '../colmap-manage/output/' + \
    data_folder_name.replace('/', '_') + '/'
output_folder_path = '../neural-angelo/output/' + \
    data_folder_name.replace('/', '_') + '/'

COLMAPManager(data_folder_path).autoGenerateData(
    remove_old, valid_percentage)
DatasetManager().generateDataset(
    'na', data_folder_path, dataset_folder_path, method_dict)

trainNA(dataset_folder_path + 'na/', method_dict['scene_type'])
