import sys
sys.path.append('../colmap-manage/')

import os

from colmap_manage.Module.colmap_manager import COLMAPManager
from colmap_manage.Module.dataset_manager import DatasetManager
from neural_angelo.Method.train import trainNA

dataset_root_folder_path = os.environ['HOME'] + '/chLi/Dataset/GS/'
sequence_name = 'haizei_1'
data_folder_path = dataset_root_folder_path + sequence_name + '/'
video_file_path = 'None'
down_sample_scale = 4

scale = 1
show_image = False
print_progress = True
remove_old = False
remain_db = True
valid_percentage = 0.8
run_mvs = False
method_dict = {
    'scene_type': 'object',
    'gpu_id_list': [2, 3, 4],
    'master_port': 29512,
}
is_copy = True

COLMAPManager(
    data_folder_path,
    video_file_path,
    down_sample_scale,
    scale,
    show_image,
    print_progress,
).autoGenerateData(
    remove_old, remain_db, valid_percentage, run_mvs=run_mvs)
DatasetManager().generateDataset(
    'na', data_folder_path, data_folder_path, method_dict, is_copy, print_progress)

trainNA(
    sequence_name,
    data_folder_path + 'na/',
    method_dict['scene_type'],
    method_dict['gpu_id_list'],
    method_dict['master_port'],
)
